### ISSUE TITLE
create post images route

### ISSUE THREAD

**Issue by sambhavsaxena** [DCRUSTODC/iic-server#1]
routes for events have been created, next is image routes, start contributing for that;

**Comment by Abhineshhh** [comment]
i am very much interested in this issue, please assign this to me

**Comment by sambhavsaxena** [comment]
sure, feel free to ask!

**Comment by Abhineshhh** [comment]
can you please give me a brief desc about this issue ..?

**Comment by sambhavsaxena** [comment]
okay so basically, there is a routes file located [here](https://github.com/DCRUSTODC/iic-server/blob/main/routes/events.js) which currently have route controllers associated with events, you will have to create a separate controller file for gallery in [this](https://github.com/DCRUSTODC/iic-server/tree/main/controllers) directory, and ensure to create controller functions for all CRUD processes.

**Comment by Ryrahul** [comment]
i can work on it

**Comment by sambhavsaxena** [comment]
@Ryrahul @AbhineshJha 
here's a screenshot of what all parameters have to be there
![image](https://github.com/DCRUSTODC/iic-server/assets/76242518/4662f1a1-aa87-482b-aa2a-bbb3208947a4)

- a title
- a desc
- an array of image urls

**Comment by Ryrahul** [comment]
Ok thanks for the description. Do you want a seprate route like /gallery or want to add the image feature in the existing routes? 
 @sambhavsaxena

**Comment by sambhavsaxena** [comment]
@Ryrahul a separate route is needed for we need to scale this feature in future

**Comment by Ryrahul** [comment]
@sambhavsaxena  check #2

**Comment by sambhavsaxena** [comment]
fixed by #2
